<a href="https://colab.research.google.com/github/r-ranjithlingaiah/NumPy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [ ]:
#what is numpy?
#it is an "core library for scientific comupting in python"(numerical operation)
#the central object in the numpy libraray is "Numpy Array"
#what is an numpy arrey?
#is a high performance multidemensional object. which is used for numerical operations


In [ ]:
#Types of array
#1D dimensional arrays
#2D
#3D

In [ ]:
#Scikit learn----->machinelearnig
#matplotlib--->DV
#pandas--->data manpulation

In [ ]:
#installation of numpy
!pip install numpy

In [ ]:
#import numpy
import numpy as np

In [ ]:
#check version of the numpy
np.__version__

'1.25.2'

In [ ]:
#central object of numpy is the array

a = np.array([1,2,3,4,5,6])
print(a)
#shape of the array #(6,)--->(rowvalue, columnvalue)--->
a.shape
#to know the type of elements in a numpy array# dtype int64 -->np.dtype
a.dtype
#number of dimensions of an array --->np.ndim
a.ndim
#i want to know the size of an aaray (total number of elements)
a.size
#i want to know the size in bytes of each element
a.itemsize

[1 2 3 4 5 6]


8

In [ ]:
#create an 2 dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(type(c))
#apply numyp methods to read an 2d array


[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [ ]:
#create 3d array
d = np.array([[[1,2,3],[4,5,6]]])
print(d)
print(type(d))
print(d.ndim)
#apply numyp methods to read an 2d array


[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


#essential method (slicing)

In [ ]:
a = np.array([1,2,3,4,5,6])
#access and chnage elements
print(a[0])
#change the element at particulat index
a[0:4] = 9,8,6,2
print(a)

1
[9 8 6 2 5 6]


In [ ]:
#element wise math operations
b = a*np.array([1,2,3,4,5,6])
print(b)
#task is to apply all arthamatic operations
print(b.sum())

[1 2 3 4 5 6]
21


#diff b/w list and array

In [ ]:
l = [1,2,3]
print(type(l))
arr = np.array([1,2,3])
print(type(arr))

#adding new item to the list
l.append(4)
print(l)
#adding element in array is not able to done because it has fixed memory
# arr.append(4)
#There are ways to add items in array , but this essentialy create new array
# l2 = l + [5]
# print(l2)


a2 = arr + np.array([4])
print(a2)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4]
[5 6 7]


In [ ]:
a3 = np.array([4,5,6])
a4 = a3 + np.array([4])
print(a4)
#broadcasting method-->single element by default add to each elect from the refrerral array


[ 8  9 10]


In [ ]:
#vector ddition:-->when your adding two arrays the array's must have same number of elements/shape
a3 = np.array([4,5,6])
a4 = a3 + np.array([7,8,9])
print(a4)

[11 13 15]


In [ ]:
#Heterogenous data:--->a collection of data which is having multiple data tpes
a = [1,2,3,4,5,6,"dog","apple"]
print(type(a))


arr= np.array(a)
print(type(arr))
print(arr)
arr.dtype

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' '3' '4' '5' '6' 'dog' 'apple']


dtype('<U21')

In [ ]:
#homohenous data---> a collection having same data type
a = [1,2,3,4]
arr1 = np.array(a)
arr1.dtype


dtype('int64')

In [ ]:
s = ['apple','bannana','kiwi']
arr2 = np.array(s)
arr2.dtype

dtype('<U7')

#Dot Product

In [ ]:
a = np.array([1,2,5])
b = np.array([3,4,6])
#sum of products of corresponding entries
# multiply each corresponding element and then take the sum

dot = 0
for i in range(len(b)):
  dot += a[i] * b[i]
print(dot)

#easy method
dot = np.dot(a,b)
print(dot)

#step by step manually
c = a*b
print(c)
d = np.sum(c)
print(d)


dot = a.dot(b)
print(dot)




41
41
[ 3  8 30]
41
41
[13 26 65]


In [ ]:
dot = a @ b
print(dot)

41


In [ ]:
dot = (a*b).sum()
print(dot)

41


In [ ]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
dot = np.dot(d,e)
print(dot)


[[[[ 30  36  42]]

  [[ 66  81  96]]

  [[102 126 150]]]]


speed test

In [ ]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
  dot = 0
  for i in range(len(A)):
    dot += A[i]*B[i]
  return dot
def dot2():
  return np.dot(a,b)
start = timer()
for t in range(T):
  dot1()
end = timer()
t1 = end - start

start = timer()
for t in range(T):
  dot2()
end = timer()
t2 = end-start

print('time with list:', t1)
print('time with array:', t2)
print('ratio',t1/t2)




time with list: 0.21689651500037144
time with array: 0.0014571649999197689
ratio 148.84828760800164


In [ ]:
s = np.random.randn(11)
print(s)

[-2.24066769 -2.16561406  1.18439075  0.13675714 -0.49766002  1.12520941
  1.11986245  2.2234713  -0.41747175  0.83547533 -0.95163268]


#multidimesional array:


In [ ]:
a = np.array([[1,2],[3,4]])
# print(a.shape)
# print(a)
#access the elements
#rows first, volumns
# print(a[0])
print(a[0][0])
#or
print(a[0,0])

1
1


In [ ]:
a = np.array([[1,2],[3,4]])

print(a)

[[1 2]
 [3 4]]


In [ ]:
#slicing
print(a[1]) # index number will give particulat entire row

[3 4]


In [ ]:
print(a[:,0]) #default index number will give particulat entire column
#[row:,column value]

[1 3]


In [ ]:
print(a[:,1]) #default index number will give particulat entire column
#[row:,column value]

[2 4]


In [ ]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
c=d[2,2]
print(c)

9


In [ ]:
#print entire column
print(d[:,2])

[3 6 9]


In [ ]:
print(d[1,1])


5


#Boolean Indexing

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
# print(a)
#print the same data with true and false
bool_idx = a > 2
print(bool_idx)

[[ True False]
 [False False]
 [False False]]


In [ ]:
#this will be a rank 1 array
print(a[bool_idx])

[1]


In [ ]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#np.where(): same size with modified values
c = np.where(a>2, a, -1)     #
print(c)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
#fancay index:access multiple index at once
a = np.array([10,2,3,4,5,6,7,8,9])
b = a
print(b)

[6 2 3]


In [ ]:
#compute indices where condition is true
import numpy as np
even = np.argwhere(a%2 ==0).flatten()
print(even)
a_even = a[even]
print(a_even)

[0 1 3 5 7]
[10  2  4  6  8]


#reshaping of an array

In [ ]:
b = np.arange(1,7)
print(b)
print(b.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
c = b.reshape((3,2))  #(1st value:row value, sencomdvalue is:column value)
print(c)
print(c.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
#reshape above array in 2 rows and 3 columns
d = c.reshape((2,3))
print(d)
print(d.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#in  reshaping newaxis is used to create new axis in the data
#needed when model require the data to be shaped in certin manner
print(b.shape)

(6,)


In [ ]:
e = a[np.newaxis,:]
print(e)
print(e.shape)

#concatenation

In [ ]:
s = np.array([[1,2],[3,4]])
h = np.array([[5,6]])
#combine above two arreys
a = np.concatenate((s,h), axis=None)
print(a)


[1 2 3 4 5 6]


In [ ]:
b = np.concatenate((s,h), axis=0)
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#add new column: note that we have to transpose b!
e = np.concatenate((s.T,h),axis = 0)
print(e)

[[1 3]
 [2 4]
 [5 6]]


In [ ]:
#hstack:stack arrays in sequence horizentally (colum wise).needs a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c)



[1 2 3 4 5 6 7 8]


In [ ]:
s = np.array([[1,2],[3,4]])
h = np.array([[5,6],[7,8]])
a = np.hstack((s,h))
print(a)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#vstack
s = np.array([[1,2],[3,4]])
h = np.array([[5,6],[7,8]])
a = np.vstack((s,h))
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#Functions and axis
a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a)
print(a.sum())  #mean()
print(a.sum(axis=None))

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
210
210


In [ ]:
print(a.sum(axis=0))

[24 26 28 30 32 34 36]


In [ ]:
print(a.sum(axis=1))

[ 70 140]


In [ ]:
#Datatypes
x = np.array([1,2])
print(x.dtype)

int64


In [ ]:
#copying of an array
a = np.array([1,2,3])
b = a
print(b)
b[0] = 42
print(a)

[1 2 3]
[42  2  3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()

b[0] = 42
print(b)
print(a)

[42  2  3]
[1 2 3]


#Generating Arrays

In [ ]:
#genarrate 2d zeros array
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b = np.ones((3,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#specif value generating
c = np.full((3,3),5.0)
print(c)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


#Random number

In [ ]:
a = np.random.random((3,2)) #uniform 0-1 distridution
print(a)

[[0.09898455 0.1735146 ]
 [0.08340695 0.06506432]
 [0.28845802 0.32291363]]


In [ ]:
b = np.random.randn(3,2) #normal/gussian disribution
print(b)

[[ 2.70893177e-01 -1.98603454e+00]
 [ 2.40135438e-01 -4.49286622e-01]
 [ 1.27750818e+00  8.30405638e-04]]


In [ ]:
d = np.random.randn(10,3)
print(d.mean(),d.var(),d.std())

0.03194616798422389 1.270742517971494 1.1272721578977696
